// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Trade.Infrastructure.Persistence;

#nullable disable

namespace Trade.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(TradeReviewerDbContext))]
    partial class TradeReviewerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("Trade.Domain.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<decimal>("AccountBalance")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_balance");

                    b.Property<string>("AccountName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("account_name");

                    b.HasKey("Id");

                    b.HasIndex("AccountName")
                        .IsUnique();

                    b.ToTable("accounts", (string)null);
                });

            modelBuilder.Entity("Trade.Domain.Entities.Trade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<int>("AccountId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("account_id");

                    b.Property<DateOnly?>("CloseDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("close_date");

                    b.Property<decimal?>("ClosePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("close_price");

                    b.Property<decimal>("CurrentPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("current_price");

                    b.Property<decimal>("EntryPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("entry_price");

                    b.Property<DateOnly>("OpenDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("open_date");

                    b.Property<decimal>("PositionSize")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT")
                        .HasColumnName("position_size");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("stock_name");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("StockName");

                    b.ToTable("trades", (string)null);
                });

            modelBuilder.Entity("Trade.Domain.Entities.TradeSignal", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<string>("Direction")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT")
                        .HasColumnName("direction");

                    b.Property<DateOnly>("SignalDate")
                        .HasColumnType("TEXT")
                        .HasColumnName("signal_date");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("stock_name");

                    b.HasKey("Id");

                    b.HasIndex("StockName");

                    b.ToTable("trade_signals", (string)null);
                });

            modelBuilder.Entity("Trade.Domain.Entities.WatchlistItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DateAdded")
                        .HasColumnType("TEXT")
                        .HasColumnName("date_added");

                    b.Property<string>("Notes")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("notes");

                    b.Property<string>("StockName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT")
                        .HasColumnName("stock_name");

                    b.HasKey("Id");

                    b.HasIndex("StockName")
                        .IsUnique();

                    b.ToTable("watchlist", (string)null);
                });

            modelBuilder.Entity("Trade.Domain.Entities.Trade", b =>
                {
                    b.HasOne("Trade.Domain.Entities.Account", "Account")
                        .WithMany("Trades")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Trade.Domain.Entities.WatchlistItem", "WatchlistItem")
                        .WithMany("Trades")
                        .HasForeignKey("StockName")
                        .HasPrincipalKey("StockName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("WatchlistItem");
                });

            modelBuilder.Entity("Trade.Domain.Entities.TradeSignal", b =>
                {
                    b.HasOne("Trade.Domain.Entities.WatchlistItem", "WatchlistItem")
                        .WithMany("TradeSignals")
                        .HasForeignKey("StockName")
                        .HasPrincipalKey("StockName")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WatchlistItem");
                });

            modelBuilder.Entity("Trade.Domain.Entities.Account", b =>
                {
                    b.Navigation("Trades");
                });

            modelBuilder.Entity("Trade.Domain.Entities.WatchlistItem", b =>
                {
                    b.Navigation("TradeSignals");

                    b.Navigation("Trades");
                });
#pragma warning restore 612, 618
        }
    }
}
